name: flutter_flix_id
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.9
  firebase: ^9.0.3
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  firebase_app_check: ^0.3.2+9
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
